### ISSUE TITLE
Error for Artifactory 

### ISSUE THREAD

**Issue by ashishsoni** [amesken/cd-tool-stack#2]
Downloading: http://172.17.0.4:8081/artifactory/org/springframework/boot/spring-boot-starter-parent/1.2.1.RELEASE/spring-boot-starter-parent-1.2.1.RELEASE.pom

[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for de.codecentric:conference-app:3.0.0: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:1.2.1.RELEASE from/to artifactory (http://172.17.0.4:8081/artifactory): Connect to 172.17.0.4:8081 [/172.17.0.4] failed: Connection refused and 'parent.relativePath' points at no local POM @ line 18, column 10
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]  
[ERROR]   The project de.codecentric:conference-app:3.0.0 (/var/jenkins_home/jobs/conference-app-2-sonar-analysis/workspace/app/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for de.codecentric:conference-app:3.0.0: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:1.2.1.RELEASE from/to artifactory (http://172.17.0.4:8081/artifactory): Connect to 172.17.0.4:8081 [/172.17.0.4] failed: Connection refused and 'parent.relativePath' points at no local POM @ line 18, column 10 -> [Help 2]
[ERROR]

**Comment by amesken** [comment]
issue has no relevance to the cd-tool-stack code offered here
